# Generated by Django 3.2.8 on 2021-12-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Page_name', models.CharField(max_length=70)),
                ('Page_cat', models.CharField(max_length=70)),
                ('Page_publish_date', models.DateField()),
            ],
        ),
    ]
